#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /root/nezha-agent -s tz.vip1024.cf:5555 -p fee2a4d018c17155b8 -d
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
    killall nezha-agent
}

restart() {
	stop
	sleep 2
	start
}
